# If the plugin should send a message on startup if there is a new version available
notify-updates: true

# Using MiniMessage format, see https://docs.advntr.dev/minimessage/format.html
prefix:
  # The normal prefix that's mostly used.
  normal: '<b><gradient:#9156F5:#E23DC5>EffectMaster<reset> <#7d7d7d>» <#bfbfbf>'

  # Some messages are very long. So this shorter version will be used.
  short: '<b><#b34ce6>E<#bd49e1>M<reset> <#7d7d7d>» <#bfbfbf>'